### ISSUE TITLE
Encoder Ticks | Odometry | Goal AR Tags

### ISSUE THREAD

**Issue by Spartan-Velanjeri** [olive-robotics/bots_bento_icra24#4]
Greetings,

1. From the base_control.py, I realised that we are directly giving velocity values to the wheels in order to move them around. Apart from Position or Velocity, is there any way to control the wheels? i.e. through Encoder Ticks and so on.
2. Do you have any code suggestion or boilerplate for the wheel odometry code ? 
3. Can we already fix the positions of each AR Tag at the goal pose for the pallets in the map, since it is anyways going to be fixed?

Thank you !
Parthan

**Comment by cxdcxd** [comment]
From the base_control.py, I realised that we are directly giving velocity values to the wheels in order to move them around. Apart from Position or Velocity, is there any way to control the wheels? i.e. through Encoder Ticks and so on.

you publish the goal velocity or position and the motor will control the rest. But yes you have the feedback from the wheels like the current velocity, position and the effort of the servo. It will be the standard joint_status message. 

https://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/JointState.html

Do you have any code suggestion or boilerplate for the wheel odometry code ?

No we dont have anything for odometery or slam or localization related examples. This is part of the competition. 

Can we already fix the positions of each AR Tag at the goal pose for the pallets in the map, since it is anyways going to be fixed?

Yes the position for the goal position of the pallets are fixed and its a zone not a point even. You should park the pallet in the zone and the goal zones are fixed.

**Comment by Spartan-Velanjeri** [comment]
I have another questions with respect to the topics getting published from the Servo

According to the [Docs](https://master.d3vki0gnoe8b4b.amplifyapp.com/hardware/servo/servo.html#ros-topics-and-services), it says there's a magnet/angle and /magnet/moving_average which is supposed to give the current angular position of the servo in radians

So this will basically be giving out angle values between 0 and 2*Pi radians only or will it go on adding after 2PI as well (meaning doesn't go back to 0 after it reaches one whole rotation)

In a sense, this will be comparable to the position output coming from the .../joint topic right?

Thank you !

**Comment by cxdcxd** [comment]
In the latest update which we are working on we will publish joint state only. In the joint state you will get a sensor_msgs::msg::JointState message with position, velocity and effort. But yes the position will be between 0 and 2Pi radian. It will get zero every time it pass the zero position. You can use the velocity of the motor to have a continues position estimate by knowing the wheel size.

**Comment by cxdcxd** [comment]
Update: For this update we will publish the continues and non continues encoders too. This is confirmed.

**Comment by Spartan-Velanjeri** [comment]
If I understand this right, continuous encoders are when the servo  can rotate continuously in both directions, rather than being limited to a specific range of motion and non continuous encoders are like for a defined range ?

**Comment by cxdcxd** [comment]
yes, now in the wheel mode motion control the position output is continues radian rotation and not limited to any range.

**Comment by Spartan-Velanjeri** [comment]
> In the latest update which we are working on we will publish joint state only. In the joint state you will get a sensor_msgs::msg::JointState message with position, velocity and effort. But yes the position will be between 0 and 2Pi radian. It will get zero every time it pass the zero position. You can use the velocity of the motor to have a continues position estimate by knowing the wheel size.

Again just to clarify, when you say continuous radian rotation, it'll still go back zero position every time it does one full rotation?

**Comment by cxdcxd** [comment]
no, in wheel mode it will go to infinity (+ or -). And you can make it zero by calling the setZero service. It will work like a continues encoder.

**Comment by cxdcxd** [comment]
in position control mode (which you may use for hook) it will be limited in -Pi to Pi.

**Comment by Spartan-Velanjeri** [comment]
Got it ! Thank you for your super quick response!

Have a great weekend ahead !
Parthan
